apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: sykmelding-manuell
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 3
    partitions: 3
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
    localRetentionHours: 336 # 336 hours = 14 days
  acl:
    - team: teamsykmelding
      application: syfosmmottak
      access: write
    - team: teamsykmelding
      application: macgyver
      access: write
    - team: teamsykmelding
      application: syfosmmanuell-backend
      access: read