apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: syfo-narmesteleder
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 3
    partitions: 3
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: teamsykmelding
      application: syfosmaltinn
      access: readwrite   # read, write, readwrite
    - team: teamsykmelding
      application: syfonlaltinn
      access: write
    - team: default
      application: syfoservicestrangler
      access: read
    - team: teamsykmelding
      application: narmesteleder
      access: readwrite
    - team: teamsykmelding
      application: syfoservice-data-syfosmregister
      access: write
    - team: default
      application: syfomock
      access: write

