apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: dinesykmeldte-hendelser-v2
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 3
    partitions: 3
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 2952  # 4 months
  acl:
    - team: flex
      application: sykepengesoknad-narmesteleder-varsler
      access: write
    - team: team-esyfo
      application: esyfovarsel
      access: write
    - team: teamsykefravr
      application: isdialogmote
      access: write
    - team: team-esyfo
      application: syfomotebehov
      access: write
    - team: team-esyfo
      application: dinesykmeldte-backend
      access: read
