apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: syfo-narmesteleder-leesah
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: compact  # delete, compact
    minimumInSyncReplicas: 3
    partitions: 3
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
    maxCompactionLagMs: 3e+9 # ~ 35 days
    minCompactionLagMs: 2.7e+9 # ~ 31 days
  acl:
    - team: teamsykmelding
      application: narmesteleder
      access: readwrite
    - team: teamsykmelding
      application: narmesteleder-varsel
      access: read
    - team: flex
      application: sykepengesoknad-narmesteleder-varsler
      access: read
    - team: flex
      application: sykepengesoknad-ikke-sendt-altinnvarsel
      access: read
    - team: flex
      application: sykepengesoknad-backend
      access: read
    - team: flex
      application: flex-sykmeldinger-backend
      access: read
    - team: teamsykmelding
      application: narmesteleder-arbeidsforhold
      access: read
    - team: teamsykefravr
      application: isnarmesteleder
      access: read
    - team: teamsykmelding
      application: dinesykmeldte-backend
      access: read
    - team: teamsykmelding
      application: sykmeldinger-arbeidsgiver
      access: read
    - team: fager
      application: notifikasjon-bruker-api-writer
      access: read
    - team: teamsykmelding
      application: syfosmaltinn
      access: read
    - team: fager
      application: min-side-arbeidsgiver-api
      access: read
    - team: team-esyfo
      application: dinesykmeldte-backend
      access: read
    - team: teamsykmelding
      application: sykmeldinger-backend-kafka
      access: read
