apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: ok-sykmelding
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 3
    partitions: 10
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: teamsykmelding
      application: syfosmmottak
      access: write
    - team: teamsykmelding
      application: syfosmmanuell-backend
      access: write
    - team: teamsykmelding
      application: syfosmpapirmottak
      access: write
    - team: teamsykmelding
      application: smregistrering-backend
      access: write
    - team: teamsykmelding
      application: syk-dig-backend
      access: write
    - team: teamsykmelding
      application: syfosmregister
      access: readwrite
    - team: teamsykmelding
      application: syfosmvarsel
      access: read
    - team: teamsykmelding
      application: syfosmsak-stream
      access: read
    - team: teamsykmelding
      application: syfosminfotrygd
      access: read
    - team: teamsykmelding
      application: syfosmarena-stream
      access: read
    - team: teamsykmelding
      application: sparenaproxy
      access: read
    - team: disykefravar
      application: dvh-sykm-konsument
      access: read
    - team: teamsykefravr
      application: isdialogmelding
      access: read
    - team: teamsykmelding
      application: sykmeldinger-backend-kafka
      access: read
    - team: teamsykmelding
      application: k143566
      access: read
