apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: syfo-sendt-sykmelding
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: compact  # delete, compact
    minimumInSyncReplicas: 3
    partitions: 3
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: teamsykmelding
      application: syfosmregister
      access: write
    - team: teamsykmelding
      application: syfosmaltinn
      access: read
    - team: teamsykmelding
      application: narmesteleder-varsel
      access: read
    - team: teamsykmelding
      application: sykmeldinger-arbeidsgiver
      access: read
    - team: flex
      application: sykepengesoknad-backend
      access: read
    - team: flex
      application: flex-syketilfelle
      access: read
    - team: flex
      application: sykepengesoknad-altinn
      access: read
    - team: teamsykmelding
      application: dinesykmeldte-backend
      access: read
    - team: teamsykmelding
      application: macgyver
      access: readwrite
    - team: teamsykmelding
      application: dinesykmeldte-kafka
      access: read
    - team: fager
      application: min-side-arbeidsgiver-api
      access: read
    - team: teamsykmelding
      application: sykmeldinger-backend-kafka
      access: read
