name: Deploy to dev
on:
  push:
    branches:
      - '*'
      - '!main'
env:
  TOPIC_FILES: topics/syfo-nl-request.yaml,topics/syfo-nl-invalid.yaml,topics/dev/syfo-narmesteleder.yaml,topics/syfo-narmesteleder-leesah.yaml,topics/syfo-sendt-sykmelding.yaml,topics/syfo-bekreftet-sykmelding.yaml,topics/syfo-mottatt-sykmelding.yaml,topics/dinesykmeldte-hendelser.yaml

jobs:
  deploy-to-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy topics to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          VAR: kafka-pool=nav-dev
          RESOURCE: ${{ env.TOPIC_FILES }}
