name: Deploy sykmelding-topics to dev
on:
  push:
    branches:
      - '**'
      - '!main'
    paths:
      - 'topics/sykmelding/**'
      - '.github/workflows/sykmelding-dev-deploy.yml'
env:
  TOPIC_FILES: topics/sykmelding/syfo-sendt-sykmelding.yaml,topics/sykmelding/syfo-bekreftet-sykmelding.yaml,topics/sykmelding/syfo-mottatt-sykmelding.yaml,topics/sykmelding/avvist-sykmelding.yaml,topics/sykmelding/manuell-behandling-sykmelding.yaml,topics/sykmelding/ok-sykmelding.yaml,topics/sykmelding/oppgave-journal-opprettet.yaml,topics/sykmelding/oppgave-produser-oppgave.yaml,topics/sykmelding/dev/papir-sm-registering.yaml,topics/sykmelding/privat-arena-input.yaml,topics/sykmelding/privat-registrer-oppgave.yaml,topics/sykmelding/privat-oppgave-retry.yaml,topics/sykmelding/privat-sminfotrygd-retry.yaml,topics/sykmelding/privat-sykmelding-sak.yaml,topics/sykmelding/sykmelding-apprec.yaml,topics/sykmelding/dev/sykmelding-manuell.yaml,topics/sykmelding/dev/sykmeldingstatus-leesah.yaml,topics/sykmelding/paragraf-i-kode.yaml,topics/sykmelding/syk-dig-oppgave.yaml,topics/sykmelding/opprett-sykmelding.yaml,topics/sykmelding/smreg-migration.yaml,topics/sykmelding/sykmeldingnotifikasjon.yaml

jobs:
  deploy-to-dev:
    name: Deploy to dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy topics to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          VAR: kafka-pool=nav-dev
          RESOURCE: ${{ env.TOPIC_FILES }}
